### ISSUE TITLE
npm run start 失败

### ISSUE THREAD

**Issue by chinalai** [Tangmore/photoEditor#1]
centry_mobile@1.0.0 start C:\Users\EDZ\Downloads\photoEditor-master\photoEditor-master
> npm run dev

> centry_mobile@1.0.0 dev C:\Users\EDZ\Downloads\photoEditor-master\photoEditor-master
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

 10% building modules 1/1 modules 0 activeevents.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRNOTAVAIL: address not available 192.168.2.223:8086
    at Server.setupListenHandle [as _listen2] (net.js:1262:19)
    at listenInCluster (net.js:1327:12)
    at doListen (net.js:1460:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Emitted 'error' event at:
    at emitErrorNT (net.js:1306:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! centry_mobile@1.0.0 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the centry_mobile@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\EDZ\AppData\Roaming\npm-cache\_logs\2020-11-26T09_35_47_987Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! centry_mobile@1.0.0 start: `npm run dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the centry_mobile@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\EDZ\AppData\Roaming\npm-cache\_logs\2020-11-26T09_35_48_025Z-debug.log

**Comment by chinalai** [comment]
npm run dev也是失败

**Comment by celizi** [comment]
1.修改photoEditor-master\config\index.js 里面的端口 为本机的端口
2. cnpm install node-sass@4.14.1
3. npm run dev

**Comment by celizi** [comment]
![image](https://user-images.githubusercontent.com/27724598/102467193-f715d600-408a-11eb-9e80-5a1769df2be8.png)
